### ISSUE TITLE
Server console flooding ~1 time per second with an error about the LaunchPad system.

### ISSUE THREAD

**Issue by Exortions** [Itchss/SkyBlock#2]
**Issue:** Server console flooding ~1 time per second with an error about the LaunchPad system.
**How to replicate:** Look at the server console.
**Version:** Latest (1.0)

**Comment by Exortions** [comment]
**Console Log Output:**
![image](https://user-images.githubusercontent.com/75327059/117501935-a0267580-af33-11eb-8783-60c2065f1e96.png)

**Comment by KingRainbow44** [comment]
run a null check on the getlaunchpadstrings, if its null then return a default value

**Comment by Exortions** [comment]
Yeah I haven't had time to code much today, going to do some bug fixing tomorrow.

**Comment by Exortions** [comment]
Working on it now 🎯

**Comment by Exortions** [comment]
Fixed it :)
