### ISSUE TITLE
Legal Notice: You cannot distribute Minecraft's Source Code.

### ISSUE THREAD

**Issue by KingRainbow44** [Itchss/SkyBlock#4]
Saving you from something (even though you have a small project) huge.
You cannot distribute Minecraft's source code. This is the reason why CraftBukkit & Spigot had to switch to BuildTools.

Files to Delete & Add to .gitignore:
- dependencies/apis/craftbukkit-1.8.8-R0.1-SNAPSHOT.jar
- dependencies/apis/spigot-api-1.8.8-R0.1-SNAPSHOT.jar

**Comment by KingRainbow44** [comment]
I would like to add: Even though you aren't distributing the source code, it could still be illegal since the .jar files aren't obfuscated (unlike Minecraft's .jar).

**Comment by Exortions** [comment]
Fixed lol I put those jars there just in case I needed to re-download them :p
